In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [3]:
import pandas as pd
import numpy as np

In [4]:
# dataset.data isse chaaro data aajenge sepal length and all
df = pd.DataFrame(dataset.data , columns=dataset.feature_names)

In [5]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
df['target'] = dataset.target

In [7]:
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
145       2  
146       2  
147       2  
148       2  
149       2

In [8]:
df_copy = df[df['target'] != 2]

In [9]:
df_copy.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
95                5.7               3.0                4.2               1.2   
96                5.7               2.9                4.2               1.3   
97                6.2               2.9                4.3               1.3   
98                5.1               2.5                3.0               1.1   
99                5.7               2.8                4.1               1.3   

    target  
95       1  
96       1  
97       1  
98       1  
99       1

In [10]:
# Independent & Dependent Features
X = df_copy.iloc[:,:-1]

In [11]:
y = df_copy.iloc[:,-1]

In [12]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [13]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20, random_state=42)

In [16]:
classifier = LogisticRegression()

In [17]:
classifier.fit(X_train , y_train)

LogisticRegression()

In [18]:
classifier.predict_proba(X_test)

array([[0.00118085, 0.99881915],
       [0.01580857, 0.98419143],
       [0.00303433, 0.99696567],
       [0.96964813, 0.03035187],
       [0.94251523, 0.05748477],
       [0.97160984, 0.02839016],
       [0.99355615, 0.00644385],
       [0.03169836, 0.96830164],
       [0.97459743, 0.02540257],
       [0.97892756, 0.02107244],
       [0.95512297, 0.04487703],
       [0.9607199 , 0.0392801 ],
       [0.00429472, 0.99570528],
       [0.9858324 , 0.0141676 ],
       [0.00924893, 0.99075107],
       [0.98144334, 0.01855666],
       [0.00208036, 0.99791964],
       [0.00125422, 0.99874578],
       [0.97463766, 0.02536234],
       [0.96123726, 0.03876274]])

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [22]:
print((confusion_matrix(y_pred , y_test)))
print((accuracy_score(y_pred , y_test)))
print((classification_report(y_pred , y_test)))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [23]:
# Hyperparamter Tuning

In [24]:
# 1. Grid Search CV

In [25]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [26]:
paramters = {'penalty' : ('l1' , 'l2' , 'elasticnet' , None) , 'C' : [1,10,20]} 

In [27]:
clf = GridSearchCV(classifier , param_grid = paramters , cv = 5)

In [28]:
## Splitting of Train data to validation data
clf.fit(X_train , y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [29]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [30]:
classifier = LogisticRegression(C=1 , penalty = 'l2')

In [31]:
classifier.fit(X_train , y_train)

LogisticRegression(C=1)

In [32]:
## Prediction
# ye change hoga abhi toh lagbhag same hi aarha hai jab hmare paas bada data hoga
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [33]:
## Reandomized Searchcv
from sklearn.model_selection import RandomizedSearchCV

In [34]:
random_clf = RandomizedSearchCV(LogisticRegression() , param_distributions=paramters , cv = 5)

In [35]:
random_clf.fit(X_train , y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elasticnet',
                                                    None)})

In [36]:
random_clf.best_params_

{'penalty': 'l2', 'C': 20}

In [37]:
classifer = LogisticRegression(penalty = 'l2' , C=20)

In [38]:
classifier.fit(X_train , y_train)

LogisticRegression(C=1)

In [39]:
y_pred = classifier.predict(X_test)

In [40]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [41]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[12  0]
 [ 0  8]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

