In [2]:
# Label and Ordinal Encoder
# 1. Label Encoder

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.DataFrame({
    'color' : ['red' , 'blue' , 'green' , 'red' , 'blue']
})

In [6]:
encoder = LabelEncoder()

In [8]:
encoder.fit_transform(df[['color']])

/Users/apple/opt/anaconda3/lib/python3.9/site-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 2, 0])

In [9]:
encoder.fit_transform(df['color'])

array([2, 0, 1, 2, 0])

In [10]:
# 2. Ordinal Encoder

In [14]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# create a simple data frame with an ordinal variable
df = pd.DataFrame({
    'size' : ['small' , 'medium' , 'large' , 'medium' , 'small' , 'large']
})

In [15]:
encoder = OrdinalEncoder(categories=[['small' , 'medium' , 'large']])

In [16]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

Ques. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.

In [17]:
df1 = pd.DataFrame({
    'color' : ['red' , 'green' , 'blue'],
    'size' : ['small' , 'medium' , 'large'],
    'material' : ['wood' , 'metal' ,'plastic']
})

In [18]:
encoder = LabelEncoder()

In [19]:
df1['color'] = encoder.fit_transform(df1['color'])
df1['size'] = encoder.fit_transform(df1['size'])
df1['material'] = encoder.fit_transform(df1['material'])

In [20]:
df1

color  size  material
0      2     2         2
1      1     1         0
2      0     0         1

Ques. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

In [21]:
data = np.array([[30, 40000, 12],
                 [35, 50000, 16],
                 [25, 30000, 14],
                 [40, 60000, 18],
                 [28, 45000, 15]])

<IPython.core.display.Javascript object>

In [24]:
cov_matrix = np.cov(data , rowvar = False)

<IPython.core.display.Javascript object>

In [25]:
cov_matrix

array([[3.53e+01, 6.25e+04, 1.00e+01],
       [6.25e+04, 1.25e+08, 2.00e+04],
       [1.00e+01, 2.00e+04, 5.00e+00]])