In [1]:
import numpy as np

In [2]:
# Numpy - Array Manipulations

In [3]:
arr = np.random.randint(1,10,(3,4))

In [4]:
arr

array([[5, 3, 8, 7],
       [5, 6, 3, 3],
       [1, 7, 1, 9]])

In [5]:
arr.reshape(6,2)

array([[5, 3],
       [8, 7],
       [5, 6],
       [3, 3],
       [1, 7],
       [1, 9]])

In [6]:
arr.reshape(2,6)

array([[5, 3, 8, 7, 5, 6],
       [3, 3, 1, 7, 1, 9]])

In [9]:
# arr.reshape(2,7) error becuase we have 12 elements only and 7*2 = 14
arr.reshape(2,-299448) # khud smajjega

array([[5, 3, 8, 7, 5, 6],
       [3, 3, 1, 7, 1, 9]])

In [10]:
arr.T

array([[5, 5, 1],
       [3, 6, 7],
       [8, 3, 1],
       [7, 3, 9]])

In [11]:
arr

array([[5, 3, 8, 7],
       [5, 6, 3, 3],
       [1, 7, 1, 9]])

In [12]:
arr.flatten()

array([5, 3, 8, 7, 5, 6, 3, 3, 1, 7, 1, 9])

In [13]:
arr1 = np.array([1,2,3,3,4])

In [14]:
arr1.ndim

1

In [17]:
# uska dimension 1 se 2 mein change krdiya and axis = 1 -> column wise
np.expand_dims(arr1 , axis = 1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [18]:
np.expand_dims(arr1 , axis = 0)

array([[1, 2, 3, 3, 4]])

In [19]:
arr

array([[5, 3, 8, 7],
       [5, 6, 3, 3],
       [1, 7, 1, 9]])

In [20]:
np.squeeze(arr)

array([[5, 3, 8, 7],
       [5, 6, 3, 3],
       [1, 7, 1, 9]])

In [21]:
data = np.array([[1] , [2] , [3]])

In [22]:
data

array([[1],
       [2],
       [3]])

In [23]:
# 2d se 1d array krdiya
np.squeeze(data)

array([1, 2, 3])

In [24]:
arr1 

array([1, 2, 3, 3, 4])

In [25]:
np.repeat(arr1 , 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [27]:
np.roll(arr1 , 2)
# ye ghuma rha hai, sara data ko 2 2 place se shift krdega

array([3, 4, 1, 2, 3])

In [28]:
arr1

array([1, 2, 3, 3, 4])

In [29]:
# 2d array banayega or rakhdega diagonals pe
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [30]:
# Numpy - Binary Operators

In [31]:
arr1 = np.random.randint(1,10 , (3,4))

In [32]:
arr2 = np.random.randint(1,10 , (3,4))

In [33]:
arr1

array([[9, 1, 1, 4],
       [9, 6, 7, 8],
       [4, 9, 7, 6]])

In [34]:
arr2

array([[3, 8, 6, 1],
       [5, 3, 5, 6],
       [1, 1, 5, 2]])

In [35]:
arr1+arr2

array([[12,  9,  7,  5],
       [14,  9, 12, 14],
       [ 5, 10, 12,  8]])

In [36]:
arr1*arr2

array([[27,  8,  6,  4],
       [45, 18, 35, 48],
       [ 4,  9, 35, 12]])

In [37]:
arr1/arr2

array([[3.        , 0.125     , 0.16666667, 4.        ],
       [1.8       , 2.        , 1.4       , 1.33333333],
       [4.        , 9.        , 1.4       , 3.        ]])

In [38]:
arr1-arr2

array([[ 6, -7, -5,  3],
       [ 4,  3,  2,  2],
       [ 3,  8,  2,  4]])

In [39]:
arr1%arr2

array([[0, 1, 1, 0],
       [4, 0, 2, 2],
       [0, 0, 2, 0]])

In [40]:
arr1**arr2 # (power arr1 element to power arr2)

array([[   729,      1,      1,      4],
       [ 59049,    216,  16807, 262144],
       [     4,      9,  16807,     36]])

In [43]:
arr1&arr2

array([[1, 0, 0, 0],
       [1, 2, 5, 0],
       [0, 1, 5, 2]])

In [41]:
arr1

array([[9, 1, 1, 4],
       [9, 6, 7, 8],
       [4, 9, 7, 6]])

In [42]:
arr2

array([[3, 8, 6, 1],
       [5, 3, 5, 6],
       [1, 1, 5, 2]])

In [44]:
~arr1

array([[-10,  -2,  -2,  -5],
       [-10,  -7,  -8,  -9],
       [ -5, -10,  -8,  -7]])

In [45]:
arr1|arr2

array([[11,  9,  7,  5],
       [13,  7,  7, 14],
       [ 5,  9,  7,  6]])

In [47]:
arr1>arr2

array([[ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [48]:
#Numpy - String Functions.

In [49]:
arr = np.array(['sudh' , "Kumar"])

In [50]:
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [51]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [52]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [54]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [55]:
#Numpy - Mathematical Functions.

In [56]:
arr1

array([[9, 1, 1, 4],
       [9, 6, 7, 8],
       [4, 9, 7, 6]])

In [57]:
np.sin(arr1)

array([[ 0.41211849,  0.84147098,  0.84147098, -0.7568025 ],
       [ 0.41211849, -0.2794155 ,  0.6569866 ,  0.98935825],
       [-0.7568025 ,  0.41211849,  0.6569866 , -0.2794155 ]])

In [58]:
np.cos(arr1)

array([[-0.91113026,  0.54030231,  0.54030231, -0.65364362],
       [-0.91113026,  0.96017029,  0.75390225, -0.14550003],
       [-0.65364362, -0.91113026,  0.75390225,  0.96017029]])

In [59]:
np.tan(arr1)

array([[-0.45231566,  1.55740772,  1.55740772,  1.15782128],
       [-0.45231566, -0.29100619,  0.87144798, -6.79971146],
       [ 1.15782128, -0.45231566,  0.87144798, -0.29100619]])

In [60]:
np.tanh(arr1) # hyper tangent

array([[0.99999997, 0.76159416, 0.76159416, 0.9993293 ],
       [0.99999997, 0.99998771, 0.99999834, 0.99999977],
       [0.9993293 , 0.99999997, 0.99999834, 0.99998771]])

In [61]:
np.log10(arr1)

array([[0.95424251, 0.        , 0.        , 0.60205999],
       [0.95424251, 0.77815125, 0.84509804, 0.90308999],
       [0.60205999, 0.95424251, 0.84509804, 0.77815125]])

In [62]:
np.exp(arr1)

array([[8.10308393e+03, 2.71828183e+00, 2.71828183e+00, 5.45981500e+01],
       [8.10308393e+03, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [5.45981500e+01, 8.10308393e+03, 1.09663316e+03, 4.03428793e+02]])

In [63]:
np.sqrt(arr1)

array([[3.        , 1.        , 1.        , 2.        ],
       [3.        , 2.44948974, 2.64575131, 2.82842712],
       [2.        , 3.        , 2.64575131, 2.44948974]])

In [64]:
np.power(arr1,2)

array([[81,  1,  1, 16],
       [81, 36, 49, 64],
       [16, 81, 49, 36]])

In [65]:
np.mean(arr1)

5.916666666666667

In [67]:
np.median(arr1)

6.5

In [68]:
np.std(arr1)

2.752524094152291

In [69]:
np.var(arr1)

7.576388888888889

In [70]:
np.min(arr1)

1

In [71]:
np.max(arr1)

9