In [11]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [12]:
type(list_)

list

In [13]:
array_list.dtype

dtype('<U1')

Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.

In [17]:
for i in list_:
    print (type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [18]:
for i in array_list:
    print (type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

In [19]:
array_list = np.array(object = list_, dtype = int)

In [20]:
array_list

array([1, 2, 3, 4, 5])

In [21]:
for i in array_list:
    print (type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [22]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
    
(i) shape

(ii) size

In [23]:
np.shape(num_list)

(2, 3)

In [24]:
np.shape(num_array)

(2, 3)

In [25]:
np.size(num_array)

6

In [27]:
num_array.size

6

In [28]:
num_array.shape

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [32]:
np.fromfunction(lambda x,y : x*y*0 , (3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [35]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
l = [1,1,1,1,1]
np.diag(l)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])